name: Build, test and push docker image

on:
  workflow_call:
    inputs:
      DOCKER_REPOSITORY:
        description: The Docker repository consisting of organization/user name and project name.
        required: true
        type: string

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Fetch release tag marked as latest
        run: |
          echo "LATEST_TAG=$(curl -sSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${{ github.api_url }}/repos/${{ github.repository }}/releases/latest" \
          | jq -r .tag_name)" >> $GITHUB_ENV

      - name: Specify docker image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ inputs.DOCKER_REPOSITORY }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ github.ref_name == env.LATEST_TAG }}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=sha

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}

      - name: Sync README with Docker Hub description
        if: ${{ github.ref_name == env.LATEST_TAG }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ inputs.DOCKER_REPOSITORY }}
          short-description: ${{ github.event.repository.description }}
