name: Boot a staging environment using PullPreview

on:
  workflow_call:
    inputs:
      pullpreview-admins:
        description: A comma separated list of users which will have SSH access to the Lightsail instance.
        required: false
        default: @collaborators/push
        type: string
      env-file:
        description: The content of a file which should be written into the .env file.
        required: false
        type: string
      instance-type:
        description: The Lightsail instance type used for the staging environment.
        required: false
        default: nano
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read # to fetch code (actions/checkout)
      deployments: write # to delete deployments
      pull-requests: write # to remove labels
      statuses: write # to create commit status
    steps:
      - uses: actions/checkout@v4

      - name: Generate .env file
        env:
          ENV_FILE: ${{ inputs.env-file }}
          BASIC_AUTH: ${{ secrets.BASIC_AUTH }}
        run: |
          cp .env.example .env
          echo "$ENV_FILE" >> .env
          echo "$BASIC_AUTH" > .htpasswd

      - uses: pullpreview/action@v5
        with:
          # Those GitHub users will have SSH access to the servers
          admins: ${{ inputs.pullpreview-admins }}
          # Use the cidrs option to restrict access to the live environments to specific IP ranges
          cidrs: "0.0.0.0/0"
          compose_files: docker-compose.pullpreview.yml
          # The preview URL will target this port
          default_port: 80
          # Use a 512MB RAM instance type instead of the default 2GB
          instance_type: nano_2_0
          # Ports to open on the server
          ports: 80, 443
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_REGION: "eu-central-1"
